/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroFicha.java
 *
 * Created on 04/05/2012, 16:33:50
 */

package GUI;

import BO.FichaBO;
import DTO.FichaDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author 109005138
 */
public class CadastroFicha extends javax.swing.JFrame {

    List<FichaDTO> listObj = new ArrayList<FichaDTO>();
    FichaBO fichaBO;


    //criação das variaveis globais;
    public CadastroFicha() {

        initComponents();
                //deixar a aplicacao no centro da tela
        this.setLocationRelativeTo(null);
        //incializa a consulta para popular a lista de objt
        //funcionando os botoes << < > >>
        fichaBO = new FichaBO();
        listObj = fichaBO.pesquisar();
        if(listObj.size()>0)
            carregarTela(listObj.get(0));

    }


    public FichaDTO carregarDTO(){
        FichaDTO fichaDTO = new FichaDTO();
        if (!"".equals(jtxtmatricula.getText()))
        {
            fichaDTO.setMatricula(0);
        }

        else
            {
            fichaDTO.setMatricula(Integer.parseInt(jtxtmatricula.getText()));
            fichaDTO.setNome(jtxtNome.getText());

             }
        return fichaDTO;

    }
    public void carregarTela(FichaDTO fichaDTO){

        jtxtmatricula.setText(String.valueOf(fichaDTO.getMatricula()));
        jtxtNome.setText(fichaDTO.getNome());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jbtnAnterior = new javax.swing.JButton();
        jbtnPrimeiro = new javax.swing.JButton();
        jbtnProximo = new javax.swing.JButton();
        jbtnUltimo = new javax.swing.JButton();
        jbtnNovo = new javax.swing.JButton();
        jbtnSalvar = new javax.swing.JButton();
        jbtnExcluir = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jlblMatricula = new javax.swing.JLabel();
        jlblNome = new javax.swing.JLabel();
        jtxtmatricula = new javax.swing.JTextField();
        jtxtNome = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anterior.png"))); // NOI18N

        jbtnPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/primeiro.png"))); // NOI18N

        jbtnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proximo.png"))); // NOI18N
        jbtnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProximoActionPerformed(evt);
            }
        });

        jbtnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ultimo.png"))); // NOI18N

        jbtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/novo.png"))); // NOI18N
        jbtnNovo.setText(" Novo");
        jbtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNovoActionPerformed(evt);
            }
        });

        jbtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar.png"))); // NOI18N
        jbtnSalvar.setText("Salvar");
        jbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarActionPerformed(evt);
            }
        });

        jbtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exlcuir.jpg"))); // NOI18N
        jbtnExcluir.setText("Excluir");
        jbtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExcluirActionPerformed(evt);
            }
        });

        jbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jlblMatricula.setText("Matricula :");

        jlblNome.setText("Nome :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jbtnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblMatricula)
                            .addComponent(jlblNome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtNome)
                            .addComponent(jtxtmatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jbtnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnUltimo)
                .addGap(108, 108, 108))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnAnterior, jbtnPrimeiro, jbtnProximo, jbtnUltimo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnCancelar, jbtnExcluir, jbtnNovo, jbtnSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblMatricula)
                    .addComponent(jtxtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNome)
                    .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnExcluir)
                    .addComponent(jbtnCancelar)
                    .addComponent(jbtnSalvar)
                    .addComponent(jbtnNovo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnProximo)
                    .addComponent(jbtnUltimo)
                    .addComponent(jbtnAnterior)
                    .addComponent(jbtnPrimeiro))
                .addGap(49, 49, 49))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnAnterior, jbtnPrimeiro, jbtnProximo, jbtnUltimo});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnCancelar, jbtnExcluir, jbtnNovo, jbtnSalvar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNovoActionPerformed
        // TODO add your handling code here:

        jtxtmatricula.setText("");
        jtxtNome.setText("");
    }//GEN-LAST:event_jbtnNovoActionPerformed



    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        // TODO add your handling code here:

        if(!"".equals(jtxtmatricula.getText())){
            String nome = jtxtNome.getText();

            for(int x = 0 ; x<listObj.size() ;x++) {
                if(nome.equals(listObj.get(x).getNome())){
                    if(x-1 >= 0)
                        carregarTela(listObj.get(x-1));

                }
            }
        }
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarActionPerformed
        // TODO add your handling code here:

        fichaBO = new FichaBO();
        FichaDTO fichaDTO = new FichaDTO();

       //Pegando o valor do TXT - Matricula
        fichaDTO.setMatricula(Integer.parseInt(jtxtmatricula.getText()));
         //passando para o DTO o resultado do BO - Procurar
        fichaDTO = fichaBO.procurar(fichaDTO);
        if(fichaDTO !=null)


           fichaBO.alterar(carregarDTO());
        else{

            fichaBO.inserir(carregarDTO());
            listObj = fichaBO.pesquisar();
            carregarTela(listObj.get(listObj.size() - 1));
        }
        listObj = fichaBO.pesquisar();



    }//GEN-LAST:event_jbtnSalvarActionPerformed

    private void jbtnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProximoActionPerformed
        // TODO add your handling code here:

        if(!"".equals(jtxtmatricula.getText())){
            String nome = jtxtNome.getText();
            for(int x=0;x<listObj.size();x++) {
                if(x+1 < listObj.size()){
                    carregarTela(listObj.get(+1));
                }
            }
        }
    }//GEN-LAST:event_jbtnProximoActionPerformed

    private void jbtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExcluirActionPerformed
        // TODO add your handling code here:

        Object[]options = {"Sim" , "Não"};
      int i = JOptionPane.showOptionDialog(null,"Confirma Exclusão do Registro", "Aviso de Exclusão",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null, options, options[0]);
      if(i==JOptionPane.YES_NO_OPTION)
      {
          if(!"".equals(jtxtmatricula.getText()))
          {
              fichaBO.excluir(carregarDTO());
              listObj = fichaBO.pesquisar();
              if(listObj.size()== 0 )
                  JOptionPane.showMessageDialog(null, "Não existem dados cadastrados!","Aviso",JOptionPane.PLAIN_MESSAGE);
              else
                  carregarTela(listObj.get(0));

          }else
              JOptionPane.showMessageDialog(null,"Registro não será excluido","Aviso", JOptionPane.PLAIN_MESSAGE);

      }
    }//GEN-LAST:event_jbtnExcluirActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFicha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbtnAnterior;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnExcluir;
    private javax.swing.JButton jbtnNovo;
    private javax.swing.JButton jbtnPrimeiro;
    private javax.swing.JButton jbtnProximo;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JButton jbtnUltimo;
    private javax.swing.JLabel jlblMatricula;
    private javax.swing.JLabel jlblNome;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField jtxtmatricula;
    // End of variables declaration//GEN-END:variables

}
