/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Calculo.java
 *
 * Created on 12/03/2012, 16:08:44
 */

package exemploaplicacaografica;


import javax.swing.JOptionPane;

/**
 *
 * @author 110000827
 */
public class Calculo extends javax.swing.JFrame {

    /** Creates new form Calculo */
    public Calculo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblNum1 = new javax.swing.JLabel();
        jtxtNum1 = new javax.swing.JTextField();
        jlblNum2 = new javax.swing.JLabel();
        jtxtNum2 = new javax.swing.JTextField();
        jbtnSomar = new javax.swing.JButton();
        jlblResult = new javax.swing.JLabel();
        jbtnSubtrair = new javax.swing.JButton();
        jbtnMultiplicar = new javax.swing.JButton();
        jbtnDividir = new javax.swing.JButton();
        jbtnResto = new javax.swing.JButton();
        jlblResultado2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N

        jlblNum1.setText("Informe um número");

        jlblNum2.setText("Informe o segundo número");

        jbtnSomar.setText("Somar");
        jbtnSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSomarActionPerformed(evt);
            }
        });

        jbtnSubtrair.setText("Subtrair");
        jbtnSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubtrairActionPerformed(evt);
            }
        });

        jbtnMultiplicar.setText("Multiplicar");
        jbtnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultiplicarActionPerformed(evt);
            }
        });

        jbtnDividir.setText("Dividir");
        jbtnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDividirActionPerformed(evt);
            }
        });

        jbtnResto.setText("Resto da divisão por 2");
        jbtnResto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblNum1)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblNum2)
                                    .addComponent(jbtnSomar)
                                    .addComponent(jbtnMultiplicar)
                                    .addComponent(jbtnResto, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnDividir)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jbtnSubtrair)
                                        .addComponent(jtxtNum2))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jlblResult))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jlblResultado2)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNum1)
                    .addComponent(jtxtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNum2)
                    .addComponent(jtxtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSomar)
                    .addComponent(jbtnSubtrair))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnMultiplicar)
                    .addComponent(jbtnDividir))
                .addGap(18, 18, 18)
                .addComponent(jlblResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jlblResultado2)
                .addGap(18, 18, 18)
                .addComponent(jbtnResto)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSomarActionPerformed
        // TODO add your handling code here:

        //DECLARAR AS VARIAVEIS
        float num1,num2;

        
            num1= Float.parseFloat(jtxtNum1.getText());
            num2= Float.parseFloat(jtxtNum2.getText());
            jlblResult.setText("O resultado da soma é "+(num1 + num2));
        
       
       


    }//GEN-LAST:event_jbtnSomarActionPerformed

    private void jbtnSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubtrairActionPerformed
        // TODO add your handling code here:
        float num1,num2;

        num1= Float.parseFloat(jtxtNum1.getText());
        num2= Float.parseFloat(jtxtNum2.getText());

        jlblResult.setText("O resultado da subtração é "+(num1 - num2));

    }//GEN-LAST:event_jbtnSubtrairActionPerformed

    private void jbtnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiplicarActionPerformed
// TODO add your handling code here:
float num1,num2;

        num1= Float.parseFloat(jtxtNum1.getText());
        num2= Float.parseFloat(jtxtNum2.getText());

        jlblResult.setText("O resultado da multiplicação é "+(num1 * num2));
    }//GEN-LAST:event_jbtnMultiplicarActionPerformed

    private void jbtnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDividirActionPerformed
        // TODO add your handling code here:
        float num1,num2;

        num1= Float.parseFloat(jtxtNum1.getText());
        num2= Float.parseFloat(jtxtNum2.getText());

        jlblResult.setText("O resultado da divisão é "+(num1/num2));
    }//GEN-LAST:event_jbtnDividirActionPerformed

    private void jbtnRestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRestoActionPerformed
        // TODO add your handling code here:

        float num1,num2;

        num1= Float.parseFloat(jtxtNum1.getText());
        num2= Float.parseFloat(jtxtNum2.getText());

        jlblResult.setText("O resto da divisão por 2 do primeiro numero é "+(num1%2));
        jlblResultado2.setText("O resto da divisão por 2 do segundo numero é "+(num2%2));
    }//GEN-LAST:event_jbtnRestoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnDividir;
    private javax.swing.JButton jbtnMultiplicar;
    private javax.swing.JButton jbtnResto;
    private javax.swing.JButton jbtnSomar;
    private javax.swing.JButton jbtnSubtrair;
    private javax.swing.JLabel jlblNum1;
    private javax.swing.JLabel jlblNum2;
    private javax.swing.JLabel jlblResult;
    private javax.swing.JLabel jlblResultado2;
    private javax.swing.JTextField jtxtNum1;
    private javax.swing.JTextField jtxtNum2;
    // End of variables declaration//GEN-END:variables

}
