/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormularioObjeto.java
 *
 * Created on 23/03/2012, 16:11:22
 */

package exercicioclasse2;

import javax.swing.JOptionPane;

/**
 *
 * @author 110000827
 */
public class FormularioObjeto extends javax.swing.JFrame {

    /** Creates new form FormularioObjeto */
    public FormularioObjeto() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxbNome = new javax.swing.JTextField();
        jtxbIdade = new javax.swing.JTextField();
        jtxbAltura = new javax.swing.JTextField();
        jtxbPeso = new javax.swing.JTextField();
        jbtnIMC = new javax.swing.JButton();
        jlblIMC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText(" Idade:");

        jLabel3.setText("Altura:");

        jLabel4.setText("Peso:");

        jbtnIMC.setText("Calcular IMC");
        jbtnIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIMCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxbNome, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jtxbIdade)
                            .addComponent(jtxbAltura)
                            .addComponent(jtxbPeso)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblIMC)
                            .addComponent(jbtnIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxbIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxbAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxbPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jbtnIMC)
                .addGap(18, 18, 18)
                .addComponent(jlblIMC)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Pessoa p = new Pessoa();

      public void  pegavalor(){
        int idade;
        
        do{
        idade= Integer.parseInt(jtxbIdade.getText());
        
            JOptionPane.showMessageDialog(null, "A idade não pode ser menor do que 0");
        
        }while(idade>0);
     
    }
    private void jbtnIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIMCActionPerformed
        // TODO add your handling code here:
        
        pegavalor();
        p.setNome(jtxbNome.getText());
        p.setIdade(Integer.parseInt(jtxbIdade.getText()));
        p.setAltura(Float.parseFloat(jtxbAltura.getText()));
        p.setPeso(Float.parseFloat(jtxbPeso.getText()));
        p.calcularPesoIdeal();
        jlblIMC.setText(p.getNome()+", o resultado do seu IMC foi "+p.getSituacao());



    }//GEN-LAST:event_jbtnIMCActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioObjeto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnIMC;
    private javax.swing.JLabel jlblIMC;
    private javax.swing.JTextField jtxbAltura;
    private javax.swing.JTextField jtxbIdade;
    private javax.swing.JTextField jtxbNome;
    private javax.swing.JTextField jtxbPeso;
    // End of variables declaration//GEN-END:variables

}
