/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Formulario.java
 *
 * Created on 19/03/2012, 16:14:09
 */

package exercicioclasse01;

import javax.swing.JOptionPane;

/**
 *
 * @author 110000827
 */
public class Formulario extends javax.swing.JFrame {

    /** Creates new form Formulario */
    public Formulario() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblNome = new javax.swing.JLabel();
        jlblNota1 = new javax.swing.JLabel();
        jlblNota2 = new javax.swing.JLabel();
        jlblNota3 = new javax.swing.JLabel();
        jlblNota4 = new javax.swing.JLabel();
        jtxbNome = new javax.swing.JTextField();
        jtxbNota1 = new javax.swing.JTextField();
        jtxbNota2 = new javax.swing.JTextField();
        jtxbNota3 = new javax.swing.JTextField();
        jtxbNota4 = new javax.swing.JTextField();
        jlblRMedia = new javax.swing.JLabel();
        jlblRSituacao = new javax.swing.JLabel();
        jbtnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblNome.setText("Nome:");

        jlblNota1.setText("Nota 1:");

        jlblNota2.setText("Nota 2:");

        jlblNota3.setText("Nota 3:");

        jlblNota4.setText("Nota 4:");

        jbtnCalcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnCalcular.setText("Calcular");
        jbtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlblNome)
                        .addComponent(jlblNota1)
                        .addComponent(jlblNota2)
                        .addComponent(jlblNota3)
                        .addComponent(jlblNota4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblRMedia)
                        .addGap(39, 39, 39)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxbNota1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxbNota2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxbNota3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxbNota4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(jbtnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(406, Short.MAX_VALUE)
                .addComponent(jlblRSituacao)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNome)
                    .addComponent(jtxbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblNota1)
                            .addComponent(jtxbNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblNota2)
                            .addComponent(jtxbNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblNota3)
                            .addComponent(jtxbNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblNota4)
                            .addComponent(jtxbNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbtnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblRMedia)
                    .addComponent(jlblRSituacao))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcularActionPerformed
        // TODO add your handling code here:
        Aluno a = new Aluno();


        a.setNome(jtxbNome.getText());
        a.setNota1(Float.parseFloat(jtxbNota1.getText()));
        a.setNota2(Float.parseFloat(jtxbNota2.getText()));
        a.setNota3(Float.parseFloat(jtxbNota3.getText()));
        a.setNota4(Float.parseFloat(jtxbNota4.getText()));
        
        JOptionPane.showMessageDialog(null, "O aluno "+a.getNome()+" com média de "+a.Media()+" pontos está  "+a.Situacao()+"");
    }//GEN-LAST:event_jbtnCalcularActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCalcular;
    private javax.swing.JLabel jlblNome;
    private javax.swing.JLabel jlblNota1;
    private javax.swing.JLabel jlblNota2;
    private javax.swing.JLabel jlblNota3;
    private javax.swing.JLabel jlblNota4;
    private javax.swing.JLabel jlblRMedia;
    private javax.swing.JLabel jlblRSituacao;
    private javax.swing.JTextField jtxbNome;
    private javax.swing.JTextField jtxbNota1;
    private javax.swing.JTextField jtxbNota2;
    private javax.swing.JTextField jtxbNota3;
    private javax.swing.JTextField jtxbNota4;
    // End of variables declaration//GEN-END:variables

}
