/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroOperacao.java
 *
 * Created on 28/06/2012, 16:15:19
 */

package GUI;

import BO.AutomoveisBO;
import BO.ClientesBO;
import BO.FuncionariosBO;
import BO.OperacaoBO;
import DTO.AutomoveisDTO;
import DTO.ClientesDTO;
import DTO.FuncionariosDTO;
import DTO.OperacaoDTO;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import util.DataUtil;

/**
 *
 * @author 110000636
 */
public class CadastroOperacao extends javax.swing.JFrame {

    List<OperacaoDTO> listObj = new ArrayList<OperacaoDTO>();
    OperacaoBO operacaoBO;

    /** Creates new form CadastroOperacao */
    public CadastroOperacao() {
        initComponents();
        this.setLocationRelativeTo(null);
        operacaoBO = new OperacaoBO();
        listObj = operacaoBO.PesquisarTodos();
        if(listObj.size() > 0)
            carregarTela(listObj.get(0));
    }




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public OperacaoDTO carregarDTO(int controle){
        OperacaoDTO operacaoDTO = new OperacaoDTO();
        if("".equals(jtfcod.getText()))
            operacaoDTO.setOpr_cod(0);
        else
            operacaoDTO.setOpr_cod(Integer.parseInt(jtfcod.getText()));

        ClientesBO clientesBO = new ClientesBO();
        ClientesDTO clientesDTO = new ClientesDTO();
        clientesDTO.setCli_nome(jcbcli.getSelectedItem().toString());
        clientesDTO = clientesBO.procurarPorDescricao(clientesDTO);
        operacaoDTO.setCliente(clientesDTO);
        FuncionariosBO funcionariosBO = new FuncionariosBO();
        FuncionariosDTO funcionariosDTO = new FuncionariosDTO();
        funcionariosDTO.setFunc_nome(jcbfunc.getSelectedItem().toString());
        funcionariosDTO = funcionariosBO.procurarPorDescricao(funcionariosDTO);
        operacaoDTO.setFuncionario(funcionariosDTO);
        AutomoveisBO automoveisBO = new AutomoveisBO();
        AutomoveisDTO automoveisDTO = new AutomoveisDTO();
        automoveisDTO.setAut_placa(jcbauto.getSelectedItem().toString());
        automoveisDTO = automoveisBO.procurarPorPlaca(automoveisDTO);
        operacaoDTO.setAutomovel(automoveisDTO);
        operacaoDTO.setOpr_tipo(jcbtipoope.getSelectedItem().toString());

        if("Venda".equals(jcbtipoope.getSelectedItem().toString()))
            operacaoDTO.getAutomovel().setAut_vendido(1);
        else
            operacaoDTO.getAutomovel().setAut_vendido(0);

        if(controle == 1){
            Date hoje = new Date();
            operacaoDTO.setOpr_data(hoje);
            operacaoDTO.setOpr_hora(hoje);
        }
        return operacaoDTO;

    }

    public void carregarTela(OperacaoDTO operacaoDTO){
        jtfcod.setText(String.valueOf(operacaoDTO.getOpr_cod()));

        ClientesBO clientesBO = new ClientesBO();
        List<ClientesDTO> listClientes = clientesBO.PesquisarTodos();
        jcbcli.removeAllItems();
        for(int x = 0; x < listClientes.size(); x++){
            jcbcli.addItem(listClientes.get(x).getCli_nome());
        }
        jcbcli.setSelectedItem(operacaoDTO.getCliente().getCli_nome());

        FuncionariosBO funcionariosBO = new FuncionariosBO();
        List<FuncionariosDTO> listFuncionarios = funcionariosBO.PesquisarTodos();
        jcbfunc.removeAllItems();
        for(int x = 0; x < listFuncionarios.size(); x++){
           jcbfunc.addItem(listFuncionarios.get(x).getFunc_nome());
        }
        jcbfunc.setSelectedItem(operacaoDTO.getFuncionario().getFunc_nome());

        AutomoveisBO automoveisBO = new AutomoveisBO();
        List<AutomoveisDTO> listAutomoveis = automoveisBO.PesquisarTodos();
        jcbauto.removeAllItems();
        for(int x = 0; x < listAutomoveis.size(); x++){
            jcbauto.addItem(listAutomoveis.get(x).getAut_placa());
        }
        jcbauto.setSelectedItem(operacaoDTO.getAutomovel().getAut_placa());

        jtfmod.setText(operacaoDTO.getAutomovel().getModelo().getMod_desc());
        jtfano.setText(String.valueOf(operacaoDTO.getAutomovel().getAut_ano()));

        jcbtipoope.setSelectedItem(operacaoDTO.getOpr_tipo());

        String dt = DataUtil.DiaMesAnoStringBarra(operacaoDTO.getOpr_data());
        String hr = DataUtil.HoraMinutoAMPM(operacaoDTO.getOpr_hora());
        jlbl_datahora.setText(dt + " - " + hr);

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfcod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbcli = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbfunc = new javax.swing.JComboBox();
        jcbauto = new javax.swing.JComboBox();
        jcbtipoope = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jtfmod = new javax.swing.JTextField();
        jtfano = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jlbl_datahora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/primeiro.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ultimo.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anterior.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proximo.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/novo.png"))); // NOI18N
        jButton5.setText("Novo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar.png"))); // NOI18N
        jButton6.setText("Salvar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exlcuir.jpg"))); // NOI18N
        jButton7.setText("Excluir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jButton8.setText("Cancelar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel1.setText("codigo");

        jtfcod.setEnabled(false);

        jLabel2.setText("cliente");

        jLabel3.setText("funcionario");

        jLabel4.setText("automoveis");

        jLabel5.setText("tipo de operação");

        jcbtipoope.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Compra", "Venda" }));

        jLabel6.setText("modelo");

        jtfmod.setEnabled(false);

        jtfano.setEnabled(false);

        jLabel7.setText("ano");

        jlbl_datahora.setText("Data/Hora da Operação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbcli, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfcod, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbtipoope, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbauto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbfunc, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfano, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfmod, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlbl_datahora))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jtfcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbfunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbauto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtfmod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbtipoope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addComponent(jlbl_datahora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jtfcod.setText("");
        jtfano.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        operacaoBO = new OperacaoBO();
        if(!"".equals(jtfcod.getText())){
            operacaoBO.alterar(carregarDTO(1));
            AutomoveisBO automoveisBO = new AutomoveisBO();
            automoveisBO.alterar(carregarDTO(1).getAutomovel());
            
        }else{
            operacaoBO.inserir(carregarDTO(1));
            AutomoveisBO automoveisBO = new AutomoveisBO();
            automoveisBO.alterar(carregarDTO(1).getAutomovel());
            operacaoBO = new OperacaoBO();
            listObj = operacaoBO.PesquisarTodos();
            carregarTela(listObj.get(listObj.size() - 1));
        }
        listObj = operacaoBO.PesquisarTodos();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Object[] options = {"Sim", "Não"};
        int i = JOptionPane.showOptionDialog(null, "Confirmar exclusão do registro?", "Aviso de exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if(i == JOptionPane.YES_OPTION){
            if(!"".equals(jtfcod.getText())){
                operacaoBO = new OperacaoBO();
                operacaoBO.excluir(carregarDTO(0));
            }
            operacaoBO = new OperacaoBO();
            listObj = operacaoBO.PesquisarTodos();
            if(listObj.size() == 0){
                JOptionPane.showMessageDialog(null, "Não existem dados cadastrados", "Aviso", JOptionPane.PLAIN_MESSAGE);
            }else{
                carregarTela(listObj.get(0));
            }
        }else{
            JOptionPane.showMessageDialog(null, "Registro não será excluido", "Aviso", JOptionPane.PLAIN_MESSAGE);
        
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      if(listObj.size() > 0)
           carregarTela(listObj.get(0));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(listObj.size() > 0)
           carregarTela(listObj.get(0));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(!"".equals(jtfcod.getText())){
            int codigo = Integer.parseInt(jtfcod.getText());
            for(int x = 0; x < listObj.size(); x++){
                if(listObj.get(x).getOpr_cod()== codigo){
                    if(x - 1 >= 0){
                        carregarTela(listObj.get(x - 1));
                    }
                }
            }
        }        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                if(!"".equals(jtfcod.getText())){
            int codigo = Integer.parseInt(jtfcod.getText());
            for(int x = 0; x < listObj.size(); x++){
                if(listObj.get(x).getOpr_cod()== codigo){
                    if(x + 1 < listObj.size()){
                        carregarTela(listObj.get(x + 1));
                    }
                }
            }
        }   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(listObj.size() > 0)
           carregarTela(listObj.get(listObj.size() - 1));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroOperacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox jcbauto;
    private javax.swing.JComboBox jcbcli;
    private javax.swing.JComboBox jcbfunc;
    private javax.swing.JComboBox jcbtipoope;
    private javax.swing.JLabel jlbl_datahora;
    private javax.swing.JTextField jtfano;
    private javax.swing.JTextField jtfcod;
    private javax.swing.JTextField jtfmod;
    // End of variables declaration//GEN-END:variables

}
